# Generated by Django 4.0 on 2022-01-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('credithour', models.IntegerField(default=0)),
                ('faculty', models.CharField(choices=[('FCSE', 'FCSE'), ('FME', 'FME'), ('FEE', 'FEE'), ('FES', 'FES'), ('FMCE', 'FMCE')], default='', max_length=4)),
            ],
            options={
                'ordering': ['credithour'],
            },
        ),
    ]
