# Generated by Django 4.0 on 2022-01-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], max_length=200, null=True),
        ),
    ]
