# Generated by Django 4.0 on 2022-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0004_alter_course_options_course_lab_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('FCSE', 'FCSE'), ('FME', 'FME'), ('FEE', 'FEE'), ('FES', 'FES'), ('FMCE', 'FMCE')], max_length=4),
        ),
    ]
