# Generated by Django 4.0 on 2022-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0005_remove_course_name_alter_course_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lab_instructor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
