# Generated by Django 4.0 on 2022-01-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTEND', '0007_alter_course_options_course_lab_time_course_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credithour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
